cargo-features = ["per-package-target"]

[package]
name = "cryptos"
version = "0.1.0"
edition = "2021"
forced-target = "x86_64-unknown-none"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [ "runner" ]

[dependencies]
bootloader_api = "0.11.0-beta"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"