[package]
name = "cryptos"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["imager"]

[dependencies]
acpi = "4.1.1"
aml = "0.16.1"
bit = "0.1.1"
bitflags = "1.3.2"
conquer-once = { version = "0.3.2", default-features = false }
hashbrown = { version = "0.12.3", default-features = false, features = ["inline-more"] }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
log = { version = "0.4.17", default-features = false }
noto-sans-mono-bitmap = "0.1.5"
pcics = "0.2.0"
raw-cpuid = "10.5.0"
rcu_cell = "0.1.10"
redox_syscall = "0.3.1"
sha3 = { version = "0.10.2", default-features = false }
slab_allocator_rs = "1.0.1"
spin = "0.9.4"
spinning_top = "0.2.4"
strum = { version = "0.24.1", default-features = false }
uefi = "0.16.0"
unix_path = { version = "1.0.1", default-features = false, features = ["alloc"] }
x2apic = "0.4.1"
x86_64 = "0.14.10"
xmas-elf = "0.8.0"

[profile.release]
debug = true
debug-assertions = true
overflow-checks = true
incremental = true
codegen-units = 256

[patch.crates-io.btrfs-diskformat]
git = "https://github.com/GodTamIt/btrfs-diskformat"
branch = "master"

[dependencies.radix-tree]
git = "https://github.com/kennystrawnmusic/radix-tree"
branch = "master"
