[unstable]
bindeps = true

[alias]
bin = "run --release --package runner --"
asm = "rustc --package runner -- --emit=asm -o target/x86_64-unknown-none/debug/cryptos.S"
kclippy = "clippy --allow-dirty --fix --package runner --"
hmfs = "run --release --package hmfsprogs --"