cargo-features = ["per-package-target"]

[package]
name = "runner"
version = "0.1.0"
edition = "2021"
forced-target = "x86_64-apple-darwin" # FIXME: find a better way to do this

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cryptos = { path = "..", artifact = "bin", target = "x86_64-unknown-none" }
bootloader = "^0.11.0-beta.1"
bootloader-x86_64-uefi = { version = "^0.11.0-beta", artifact = "bin", target = "x86_64-unknown-uefi" }